version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ebook-frontend-test
    ports:
      - "3000:3000"
    restart: unless-stopped 