/**
 * GradientCover Component
 * 
 * Renders a book cover with gradient background.
 * Gradient CSS is generated by backend using sophisticated preset system.
 */

function GradientCover({ 
  title, 
  author,
  coverGradient,
  coverBgColor,
  coverTextColor,
  className = '' 
}) {
  // Fallback gradient if API data not available
  const gradient = coverGradient || 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
  const bgColor = coverBgColor || '#667eea'
  const textColor = coverTextColor || '#fff'
  
  // Truncate long titles for display on cover
  const displayTitle = title.length > 50 
    ? title.slice(0, 47) + '...' 
    : title
  
  const displayAuthor = author.length > 30 
    ? author.slice(0, 27) + '...' 
    : author

  return (
    <div 
      className={`cover-gradient relative aspect-[2/3] rounded-lg overflow-hidden ${className}`}
      style={{
        backgroundImage: gradient,
        backgroundColor: bgColor,
      }}
    >
      {/* Content overlay */}
      <div className="absolute inset-0 flex flex-col justify-between p-3">
        {/* Title area */}
        <div className="flex-1 flex items-center justify-center">
          <h3 
            className="text-center font-serif font-bold text-sm sm:text-base leading-tight px-2"
            style={{ 
              color: textColor,
              textShadow: '0 1px 4px rgba(0, 0, 0, 0.4)' 
            }}
          >
            {displayTitle}
          </h3>
        </div>
        
        {/* Author */}
        <p 
          className="text-center text-xs truncate"
          style={{ 
            color: textColor,
            opacity: 0.7,
            textShadow: '0 1px 3px rgba(0, 0, 0, 0.3)' 
          }}
        >
          {displayAuthor}
        </p>
      </div>
      
      {/* Subtle texture overlay */}
      <div 
        className="absolute inset-0 opacity-10 pointer-events-none"
        style={{
          backgroundImage: 'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 400 400\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'noiseFilter\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.9\' numOctaves=\'3\' stitchTiles=\'stitch\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23noiseFilter)\'/%3E%3C/svg%3E")'
        }}
      />
    </div>
  )
}

export default GradientCover
